GRANT SELECT ON hr.countries TO oe;
GRANT REFERENCES ON hr.countries TO oe;
GRANT SELECT ON hr.departments TO oe;
GRANT SELECT ON hr.employees TO oe;
GRANT REFERENCES ON hr.employees TO oe;
GRANT SELECT ON hr.job_history TO oe;
GRANT SELECT ON hr.jobs TO oe;
GRANT SELECT ON hr.locations TO oe;
GRANT REFERENCES ON hr.locations TO oe;